project_name: "ntest"

# before are hooks that will be run before any builds are done, so good to put install scripts and stuff that your builds need here
before:
  hooks:
    # Remove unused packaged from the build process
    - go mod tidy
    - go generate

builds:
  - main: ./main.go
    binary: ntest
    goos: ["linux", "darwin", "windows"]
    goarch: ["386", "amd64"]
    ldflags:
      - -s -w -X "github.com/bschaatsbergen/ntest/cmd.version={{.Version}}"
    env:
      - CGO_ENABLED=0

changelog:
  sort: "asc"
  filters:
    exclude: ["^docs:", "demo", "^hugo:", "Merge pull request", "Merge branch"]

brews:
  - tap:
      owner: bschaatsbergen
      name: homebrew-ntest
    name: ntest
    homepage: "https://github.com/bschaatsbergen/ntest"
    description: "ntest is a cross-platform cli app that runs multiple tests against any address."
    license: "MIT"
    skip_upload: auto
    commit_author:
      name: Bruno Schaatsbergen
      email: git@bschaatsbergen.com
    folder: Formula
    install: |-
      bin.install "ntest"
    test: |
      system "#{bin}/ntest -v"
